services:
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: ecademy
      MYSQL_ROOT_PASSWORD: ecademy321
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ecademy_data:/var/lib/mysql
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]

  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    ports:
      - "3001:3000"
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    env_file:
      - .env.production
    depends_on:
      - db
    image: "ghcr.io/mohamedaleya/ecademy:0.0.1"

volumes:
  ecademy_data:
